#GET http://localhost:4004/odata/v4/product/printhelloworld(input='Hello')

#GET http://localhost:4004/odata/v4/product/addition(num1=5,num2=10)

#GET http://localhost:4004/odata/v4/product/Myfunction(category=2)

GET http://localhost:39217/odata/v4/productshop/Product

#GET http://localhost:4004/odata/v4/productshop/Supplier